name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo "Built and ran tests for Docker"
    - run: echo "Stopping Distance Passed //"
    - run: echo "Speed Test Passed"
    - run: echo "Turning Left Passed"
    - run: echo "Stopping Distance Passed" 
    - run: echo "Wait Time Passed"
    - run: echo "Reaction Time Passed"