name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker run -i --rm --privileged --shm-size=15gb -v /etc/vulkan/icd.d/nvidia_icd.json:/etc/vulkan/icd.d/nvidia_icd.json -v ./TokenTAMUAutoDrive.txt:/batchtoken.txt -v './Final Run:/adc' -v './license.lic:/home/matlab/.local/share/MathWorks/RoadRunner/R2024b/Licenses/license.lic' --gpus all -p 5901:5901 -p 6080:6080 blubywaff/adc-cicd:24b-gpu -vnc 
