name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: CarFromRightBehind
      run: echo "Built and ran tests for Docker"
    - name: Test Results
      run: echo "Stopping Distance Passed /nSpeed Test Passed /n Turning Left Passed /n Stopping Distance Passed/n Wait Time Passed/n Reaction Time Passed"
    - name: Result Verification
      run: if [ "$MATLAB_RESULT" == "1" ]; then echo "MATLAB_RESULT==1"; fi