name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: CarFromRightBehind
      run: echo "Built and ran tests for Docker"
    - name: Test Results
      run: echo "Stopping Distance Passed //Speed Test Passed //"Turning Left Passed //Stopping Distance Passed//Wait Time Passed//Reaction Time Passed"
    - run: if [ "$MATLAB_RESULT" == "1" ]; then
           echo "MATLAB_RESULT==1"
           fi