name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: CarFromRightBehind
      run: echo "sleep 75"
    - name: Test Results
      run: echo $MAT_RES
    - name: Result Verification
      run: if [ "$MATLAB_RESULT" == "1" ]; then echo "MATLAB_RESULT==1"; fi


  
    - uses: actions/checkout@v4
    - name: Fail1
      run: echo "sleep 75"
    - name: Test Results
      run: echo $MAT_RES
    - name: Result Verification
      run: if [ "$MATLAB_RESULT" == "1" ]; then echo "MATLAB_RESULT==1"; fi



    - uses: actions/checkout@v4
    - name: Fail1246
      run: echo "sleep 75"
    - name: Test Results
      run: echo $MAT_RES
    - name: Result Verification
      run: if [ "$MATLAB_RESULT" == "1" ]; then echo "MATLAB_RESULT==1"; fi


    - uses: actions/checkout@v4
    - name: Fail4
      run: echo "sleep 75"
    - name: Test Results
      run: echo $MAT_RES
    - name: Result Verification
      run: if [ "$MATLAB_RESULT" == "1" ]; then echo "MATLAB_RESULT==1"; fi
